production:
  url: <%= ENV['DATABASE_URL'] %>
  # host: https://murmuring-lowlands-90648.herokuapp.com/

development:
  adapter: sqlite3
  encoding: unicode
  database: courses
  username: postgres
  password: Haudi
  host: localhost
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: courses
  username: postgres
  password: Haudi
  host: localhost
  pool: 5
