production:
  url: <%= ENV['DATABASE_URL'] %>
  # host: https://murmuring-lowlands-90648.herokuapp.com/

development:
  adapter: sqlite3
  encoding: unicode
  database: courses
  username: postgres
  password: 12345
  host: localhost
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: courses
  username: postgres
  password: 1234
  host: localhost
  pool: 5
