production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
development:
  adapter: sqlite3
  encoding: unicode
  database: courses
  username: postgres
  password: 12345
  host: localhost
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: courses
  username: postgres
  password: 12345
  host: localhost
  pool: 5
