production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: courses
  pool: 5
  username: thess
  password: M00dInd!g0_

test:
  adapter: postgresql
  encoding: unicode
  database: courses
  pool: 5
  username:
  password:
